### ISSUE TITLE
IdFieldDoesNotExistException Lollipop

### ISSUE THREAD

**Issue by Brblol** [epsilonlabsllc/DataManagement#6]
The library used to work fine until I upgraded to Lollipop. Now I get this error even though I haven't changed anything

**Comment by tcaputi** [comment]
I will look into this today, although my testing capabilities are somewhat limited right now...

**Comment by tcaputi** [comment]
if the code is not too sensitive, a stack trace would be very helpful. if it is sensitive and you are ok sharing it only with us (we will not use it for any purposes other than debugging) you can email it to us

**Comment by skmpowdjy** [comment]
```
net.epsilonlabs.datamanagementefficient.exception.IdFieldDoesNotExistException
at net.epsilonlabs.datamanagementefficient.library.DataUtil.getIdField(DataUtil.java:105)
at net.epsilonlabs.datamanagementefficient.library.PersistenceContext.create(PersistenceContext.java:55)
at net.epsilonlabs.datamanagementefficient.library.PersistenceContext.create(PersistenceContext.java:83)
at net.epsilonlabs.datamanagementefficient.library.PersistenceContext.create(PersistenceContext.java:83)
at net.epsilonlabs.datamanagementefficient.library.DataManager.add(DataManager.java:95)
at net.epsilonlabs.silence.EditEventActivity.handleSaveButtonClick(EditEventActivity.java:348)
at net.epsilonlabs.silence.EditEventActivity$1.onClick(EditEventActivity.java:126)
at android.view.View.performClick(View.java:4756)
at android.view.View$PerformClick.run(View.java:19749)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5221)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

Occurs in previously working code with no changes.  Google promised the new ART runtime in 5.0 would be completely backwards compatible, but obviously that's not the case.

**Comment by Brblol** [comment]
net.epsilonlabs.datamanagementefficient.exception.IdFieldDoesNotExistException
atnet.epsilonlabs.datamanagementefficient.library.DataUtil.getIdField(DataUtil.java:110)
atnet.epsilonlabs.datamanagementefficient.library.PersistenceContext.create(PersistenceContext.java:55)
atnet.epsilonlabs.datamanagementefficient.library.PersistenceContext.create(PersistenceContext.java:83)
atnet.epsilonlabs.datamanagementefficient.user.DataManager.add(DataManager.java:98)
xxxxxx.xxxxxxx.xxxx.MovieDataManager$add.doInBackground(MovieDataManager.java:132)  
xxxx.xxxxxxx.xxxx.MovieDataManager$add.doInBackground(MovieDataManager.java:1)
atandroid.os.AsyncTask$2.call(AsyncTask.java:288)
atjava.util.concurrent.FutureTask.run(FutureTask.java:237)
android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
java.lang.Thread.run(Thread.java:818)

**Comment by arunkumar9t2** [comment]
I am no expert, but I could see sweeping changes in the way reflection APIs are used. I could see in debug, fields and method are referenced as ArtMethod and ArtField. And also apparently toggling mobile data via reflection broke. [link](http://stackoverflow.com/questions/26539445/the-setmobiledataenabled-is-no-longer-callable-as-of-android-l-and-later)
Where do we stand on this now? Any possible fix could be made?

**Comment by Brblol** [comment]
@logmein3546  any idea if this issue is fixable or not? my app depends on this library and i would have to drop it if this is going to take long to fix or if its not fixable.  any idea?

**Comment by tcaputi** [comment]
i believe it is fixable, but I need a little time to look into it. I promise I will have a definite answer by the end of the night.

**Comment by tcaputi** [comment]
I am having a hard time finding any information regarding any changes to reflection in ART... In fact the only thing I found was that Object now has private fields that you should not try to muck with through reflection. It is also difficult for me to debug this issue since my phone (and debugging device) is currently out for repair. I will do my best to borrow one tomorrow to see if I can resolve this issue.

**Comment by Brblol** [comment]
Much appreciated

**Comment by Brblol** [comment]
Any luck with this? I have not been able to figure it out

**Comment by tcaputi** [comment]
fixed, get the new version and it should work

**Comment by arunkumar9t2** [comment]
Thanks :) after latest commit, everything works fine.
